namespace WeatherElectric.SplashText.Scripts.Lists;

public static class MinecraftSplashes
{
    private static readonly string[] Splashes =
    [
        "...!",
        ".party()!",
        "IS YOU! I HAVE MY FRIEND",
        "1% sugar!",
        "100% pure!",
        "10 years of Mining and Crafting! It’s a Minecraft anniversary!",
        "12 herbs and spices! It’s a parody of KFC?!",
        "12345 is a bad password! What should you do?",
        "150 bpm for 400000 minutes!",
        "150% hyperbole!",
        "20 GOTO 10!",
        "4815162342 lines of code!",
        "90% bug free!",
        "90210!",
        "A skeleton popped out!",
        "Absolutely fixed relatively broken coordinates?",
        "Absolutely no memes!",
        "Afraid of the big, black bat! You gonna run away",
        "Age of Wonders is better!",
        "Ahhhhhh!",
        "All inclusive!",
        "All is full of love! Even the Icelanders",
        "All rumors are true!",
        "\"Almost never\" is an interesting concept!",
        "Also try Braid!",
        "Also try Limbo!",
        "Also try Mount And Blade!",
        "Also try Pixeljunk Shooter!",
        "Also try Project Zomboid!",
        "Also try Super Meat Boy!",
        "Also try Terraria!",
        "Also try VVVVVV!",
        "Also try World of Goo!",
        "An illusion! What are you hiding?",
        "Any computer is a laptop if you're brave enough!",
        "A riddle, wrapped in a mystery!",
        "As seen on TV! “What the heck is this?!”",
        "Ask your doctor! If you have a syndrome,severe,headache etc",
        "\"Autological\" is…",
        "Autonomous!",
        "Awesome community!",
        "Awesome game design right there!",
        "Awesome! This is Cool",
        "Bees, bees, bees, bees!",
        "Bekarton guards the gate!",
        "Best in class!",
        "Big Pointy Teeth!",
        "Bigger than a bread box!",
        "Blue warrior shot the food!",
        "Boats FTW",
        "Boots with the fur!",
        "Bread is pain!",
        "Bring it on!",
        "Bring me Ray Cokes!",
        "Bringing home the bacon!",
        "BTAF used to be good!",
        "Buckets of lava!",
        "Buzzy Bees!",
        "Call your mother!",
        "Casual gaming!",
        "Ceci n'est pas une title screen!",
        "Check it out!",
        "Check out the far lands!",
        "Child's play!",
        "Classy!",
        "Closed source!",
        "Cloud computing!",
        "Cogito ergo sum!",
        "Collaborate and listen!",
        "Colormatic",
        "Complex cellular automata!",
        "Consummate V's!",
        "Conventional!",
        "Cow Tools!",
        "Create!",
        "Cruising streets for gold!",
        "Cześć Polsko!",
        "Déjà vu!",
        "Déjà vu!",
        "Do it all, everything!",
        "Do not distribute!",
        "Do you want to join my server?",
        "Does barrel rolls!",
        "Doesn't avoid double negatives!",
        "Doesn't use the U-word!",
        "Don't bother with the clones!",
        "Don't feed avocados to parrots!",
        "Don't feed chocolate to parrots!",
        "Don't look directly at the bugs!",
        "Don’t worry, be happy!",
        "doot doot",
        "Double buffered!",
        "Down with O.P.P.!",
        "DRR! DRR! DRR!",
        "Dungeon!",
        "DungeonQuest is unfair!",
        "Engage!",
        "Enhanced!",
        "Eple (original edit)!",
        "Euclidian!",
        "Excitement!",
        "Exclusive!",
        "Exploding creepers!",
        "Extra things!",
        "Falling off cliffs!",
        "Falling with style!",
        "Fan fiction!",
        "Fantasy!",
        "Fat free!",
        "Feature packed!",
        "Finally complete!",
        "Finally with ladders!",
        "Finger-licking!",
        "Flashing letters!",
        "Flavor with no seasoning!",
        "Flaxkikare!",
        "Fnord!",
        "Follow the train, CJ!",
        "Freaky!",
        "Free dental!",
        "From the streets of Södermalm!",
        "Full of stars!",
        "Funk soul brother!",
        "FUNKY LOL",
        "Gargamel plays it!",
        "Gasp!",
        "Getting ready to drop!",
        "Getting ready to freak!",
        "Getting ready to know!",
        "Getting ready to shock!",
        "Getting ready to show!",
        "Getting ready to speak!",
        "Ghoughpteighbteau tchoghs!",
        "Replaced molten cheese with blood?",
        "Representing Edsbyn!",
        "Reticulating splines!",
        "Ride the pig!",
        "Rise from your grave!",
        "Rita is the new top dog!",
        "Rule #1: it's never my fault",
        "Run, coward! I hunger!",
        "Ryan also has amazing hair!",
        "Scary!",
        "See you next Friday or so!",
        "Seecret Friday update!",
        "Sensational!",
        "Sexy!",
        "Should not be played while driving",
        "Singleplayer!",
        "Slow acting portals!",
        "So fresh, so clean!",
        "Something funny!",
        "Something's not quite right...",
        "So sweet, like a nice bon bon!",
        "Spiders everywhere!",
        "sqrt(-1) love you!",
        "Stay a while, stay forever!",
        "Stay a while and listen!",
        "Stop being reasonable, this is the Internet!",
        "Stop, hammertime!",
        "Strange, but not a stranger!",
        "Sublime!",
        "Supercalifragilisticexpialidocious!",
        "Survive!",
        "Switches and ores!",
        "SWM forever!",
        "Swords for everyone!",
        "Synecdoche!",
        "Take an eggbeater and beat it against a skillet!",
        "Take frequent breaks!",
        "Take her pillow!",
        "Take the elevator to the mezzanine!",
        "Technically good!",
        "Technologic!",
        "Teetsuuuuoooo!",
        "Tell your friends!",
        "Terrestrial!",
        "Testificates!",
        "Thank you for the fish!",
        "That's no moon!",
        "That's Numberwang!",
        "That's super!",
        "The bee's knees!",
        "The creeper is a spy!",
        "The sky is the limit!",
        "The sum of its parts!",
        "The true meaning of covfefe",
        "There's no stopping the Trollmaso",
        "This is good for Realms.",
        "This is my true form!",
        "This message will never appear on the splash screen, isn't that weird?",
        "This text is hard to read if you play the game at the default resolution, but at 1080p it's fine!",
        "Thousands of colors!",
        "Throw a blanket over it!",
        "Throw yourself at the ground and miss",
        "Tip your waiter!",
        "Totally forgot about Dre!",
        "Tougher than diamonds, rich like cream!",
        "Treatment for your rash!",
        "Truly gone fishing!",
        "Try it!",
        "Try the mushroom stew!",
        "Try the Nether!",
        "Twittered about!",
        "Turing complete!",
        "Tyrion would love it!",
        "Ultimate edition!",
        "umop-apisdn!",
        "Undefeated!",
        "Undocumented!",
        "Une baguette!",
        "Uninflammable!",
        "Uses LWJGL!",
        "Verlet intregration!",
        "Very fun!",
        "Very influential in its circle!",
        "Vote for net neutrality!",
        "Warning! A huge battleship \"STEVE\" is approaching fast!",
        "Water bottle!",
        "Water proof!",
        "Welcome to your Doom!",
        "What do you expect?",
        "What’s the question?",
        "What's up, Doc?",
        "Where there is not light, there can spider!",
        "Who put it there?",
        "Whoa, dude!",
        "Woah.",
        "Woo, /v/!",
        "Woo, facepunch!",
        "Woo, reddit!",
        "Woo, 2pp!",
        "Woo, somethingawful!",
        "Woo, tigsource!",
        "Woo, worldofminecraft!",
        "Wow!",
        "Yaaay!",
        "Yay, puppies for everyone!",
        "Yes, sir!",
        "You can't explain that!",
        "You're going too fast!",
        "You've got a brand new key!"
    ];

    public static string GetRandomSplash()
    {
        var rnd = new System.Random();
        var randomSplash = Splashes[rnd.Next(Splashes.Length)];
        if (randomSplash.Contains("IS YOU! I HAVE MY FRIEND"))
        {
            randomSplash = $"{Environment.UserName} IS YOU! I HAVE MY FRIEND";
        }
        return randomSplash;
    }
}